### ISSUE TITLE
Suggestion - Reset Hotkey

### ISSUE THREAD

**Issue by DJScias** [Elysia-ff/FFXIV_RotationHelper#10]
Hello there,

Apologies if this already exists, but I can't find it so I figured I'd add in request for it.

The request is simple: A reset hotkey.

Basically something you can bind and when you press it, it restarts the rotation to the beginning (like stop & start) but that way you don't have to go out of the game screen. It's useful if you miss a piece of the rotation and want to restart it or if a battle ends early.

Not sure if it's possible, feasible or (as I mentioned at the start) it already exists but I just don't know how.

**Comment by Elysia-ff** [comment]
There's an option to restart when the rotation has ended. but I assume you want to reset it while the rotation is still running.

I can add the feature similar to ACT's.
If you type '/e end' in the in-game chat, ACT will execute 'End Encounter' command.
So with this plugin, you type a line (maybe /e rotationreset ?), plugin will reset it.
Then you can bind the line to in-game macro for hot key.

Will be updated soon! :)

**Comment by DJScias** [comment]
Hello there,

You perfectly understood what I meant and the solution you're proposing is an amazing way to fix it.

Thank you for the swift response and no rush on the update. :)

**Comment by Elysia-ff** [comment]
It's been updated.
Bind `/e rotationreset` to in-game macro :)

Thanks!
