### ISSUE TITLE
DRK Delirium

### ISSUE THREAD

**Issue by TheLumi** [Elysia-ff/FFXIV_RotationHelper#13]
DRK Delirium not being triggered in Rotation Helper

30|2021-12-29T17:30:44.4970000-06:00|7B4|Delirium|0.00|1081A0BC|Kalsea Virta|1081A0BC|Kalsea Virta|03|69594|69594|8364f6b96a37cff4

Hope this helps!

**Comment by Elysia-ff** [comment]
I fixed a typo, no update needed.
Let me know if it's working.

Thanks!
