### ISSUE TITLE
Bard song abilites doesn't show up

### ISSUE THREAD

**Issue by AlexZu77** [Elysia-ff/FFXIV_RotationHelper#15]
Bard song abilities doesn't show up in the rotation overlay

**Comment by Elysia-ff** [comment]
`The Wanderer's Minuet` had the problem, `Pitch Perfect`, `Mage's Ballad`, `Bloodletter` and `Army's Paeon` was fine.

Download the new [version](https://github.com/Elysia-ff/FFXIV_RotationHelper/releases/latest) plz,  Thanks!
