### ISSUE TITLE
Monk skills missing

### ISSUE THREAD

**Issue by bubblefarts** [Elysia-ff/FFXIV_RotationHelper#18]
Monk Skills:
          Riddle of Wind
21|2022-03-14T16:47:37.1900000-04:00|1076A678|Princess Bubblefarts|64A6|Riddle of Wind|1076A678|Princess Bubblefarts|CE0E|A7F0000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|50417|50417|10000|10000|||135.02|-66.03|46.00|-3.11|50417|50417|10000|10000|||135.02|-66.03|46.00|-3.11|000029DC|0|1|78267bd619315c81
          The Forbidden Chakra
21|2022-03-14T16:51:01.5550000-04:00|1076A678|Princess Bubblefarts|DDB|the Forbidden Chakra|40000860|Striking Dummy|730203|1D8B0000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|2124811|2134350|0|10000|||134.42|-90.50|46.00|0.02|50417|50417|10000|10000|||134.69|-88.34|46.00|-3.02|000029E4|0|1|8834308178c08182

FFXIVROTATIONS.COM recently updated to fix missing skills, I don't know if the issue is with how rotationhelper grabs the rotations from the website or detecting them.

**Comment by Elysia-ff** [comment]
This plugin ignores the skills marked as 'deprecated'.
I found some 'deprecated status' are changed in the latest update of ffxivrotations.com.

And it should work since now :)
Let me know if there is another problem, thanks!
