### ISSUE TITLE
Not working post game updates?

### ISSUE THREAD

**Issue by Omnicidiel** [Elysia-ff/FFXIV_RotationHelper#20]
**What actions does not work?**

Does not work post client update

**Providing this info will help me a lot :) (optional)**
1. On ACT, Plugins -> FFXIV Settings -> Open FFXIV Log Folder
2. Open your log file with notepad.
3. Search the action's name, Find the log start with 21| or 22|
4. Copy-paste it here.
ex) 21|2021-04-19T21:20:01.2940000+09:00|12341234|Ellie Nyan|A7|Energy Drain|4000

**Comment by Elysia-ff** [comment]
Hello, sorry for the late reply.
All features worked as expected in the last test.

If you found any problem, please make a new issue :)
Thanks.
