### ISSUE TITLE
Box is blank, even with rotation loaded. 

### ISSUE THREAD

**Issue by SeraphicHaze** [Elysia-ff/FFXIV_RotationHelper#22]
**What actions does not work?**
The plugin is not working. I am getting a blank box instead of a rotation, even with rotations loaded. 

**Providing this info will help me a lot :) (optional)**

![image](https://user-images.githubusercontent.com/101298921/196038803-37432466-34db-4cbd-a970-95104a6f01ad.png)

**Comment by Code4Cookie** [comment]
#23 Fixes this issue.
