### ISSUE TITLE
Plugin doesn't appear in game

### ISSUE THREAD

**Issue by ThanatosIruga** [Elysia-ff/FFXIV_RotationHelper#4]
I updated the plugin to the latest version and now the rotation no longer appears on the screen.
Overlay and other plugins appear normally.
For some strange reason all another plugin works at fullscreen but this one no.

**Comment by Elysia-ff** [comment]
ok, I'll check. But, what is the plugin did you update? this or ffxiv_act_plugin?

and before you updated it, was it working?

**Comment by ThanatosIruga** [comment]
Sorry to respond so late, the plugin just doesnt work in fullscreen mode, work fine at window full screen.
that was the problem i was having :D

**Comment by Elysia-ff** [comment]
I found a lot of solutions that didn't make it work :(
also, MopiMopi overlay didn't work either in full screen mode. 

Let me notice what are the overlay did you check?

**Comment by Elysia-ff** [comment]
I couldn't found how to make it work on fullscreen mode and all plugins I use didn't work on it.
This won't be fixed.
