### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Sephixx** [Elysia-ff/FFXIV_RotationHelper#6]
does not work with new Shadowbringers spells.
tested with the machinist, the monk, the drk.

**Comment by Sephixx** [comment]
machinist's spells that don't work: 
- Drill
- Heated Split Shot
- Barrel Stabilizer
- Heated Slug Shot
- Air Anchor
- Heated Clean Shot
- Hypercharge
- Heat Blast

**Comment by Elysia-ff** [comment]
Duplicate of #5
