### ISSUE TITLE
There are a few issues with the way you use the ACT / FFXIV plugin API

### ISSUE THREAD

**Issue by ngld** [Elysia-ff/FFXIV_RotationHelper#8]
If you want to read the raw network lines (with the `|` delimiter), use `logInfo.originalLogLine`. The `logInfo.logLine` property is replaced with the parsed / trigger version (which uses the `:` delimiter) by the FFXIV plugin.
You should probably also skip imported log lines to avoid unnecessary slow downs during log imports. 

Never, ever, ever, ever, mess with other plugins. If you restart the FFXIV plugin, you break any other plugins that were loaded before yours which access the FFXIV plugin (i.e. OverlayPlugin).
I'm talking about this part:
https://github.com/Elysia-ff/FFXIV_RotationHelper/blob/b5bec35a545a331522275a9eba2a22b7aaa3d1b9/FFXIV_RotationHelper/Windows/FFXIV_RotationHelper.cs#L67-L99

You really shouldn't swallow exceptions like that, either, because it can easily cause headaches during troubleshooting. At the very least, log it somewhere. You can use ACT's `ActGlobals.oFormActMain.WriteExceptionLog()` for that if you don't want to manage your own log.

**Comment by Elysia-ff** [comment]
I copy-pasted that part from someone's code :3 and I didn't know it'll be a problem :(
I found `logInfo.originalLogLine` too late to update it so I left it haha..

I'll fix those things if I make new plugin. Thanks!
