### ISSUE TITLE
Doesn't work if i'm loading a rotation

### ISSUE THREAD

**Issue by ghost** [Elysia-ff/FFXIV_RotationHelper#9]
Version v3.2.0.0:

Hi, if i load a rotation, ACT comes up with this error message:

Unhandled Exception in ACT

CsvHelper.BadDataException - You can ignore bad data by setting BadDataFound to null.
   bei CsvHelper.CsvParser.<ReadAsync>d__16.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei CsvHelper.CsvReader.<ReadAsync>d__20.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei FFXIV_RotationHelper.DB.<LoadAdjustTable>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FFXIV_RotationHelper.DB.<LoadAsync>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FFXIV_RotationHelper.FFXIV_RotationHelper.<GetRotationAsync>d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FFXIV_RotationHelper.FFXIV_RotationHelper.<LoadBtn_Click>d__6.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

CsvHelper.CsvParser+<ReadAsync>d__16, CsvHelper, Version=12.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823

**Comment by Elysia-ff** [comment]
It seems to be default locale issue. I released a new version, let me know if it's working :)
https://github.com/Elysia-ff/FFXIV_RotationHelper/releases/tag/v3.3.0.0

**Comment by ghost** [comment]
ty now it works :)
